<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><AssemblyName>SyntheticEvaluationPopulationIntegration.IntegrationTests</AssemblyName></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../../src/server/modules/SyntheticEvaluationPopulationIntegration/SyntheticEvaluationPopulationIntegration.csproj" /></ItemGroup>
</Project>
