<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="../../../src/server/modules/SyntheticOutcomePriority/SyntheticOutcomePriority.csproj" /><Compile Include="../../unit/SyntheticOutcomePriority.Tests/Fixtures.cs" Link="Fixtures.cs" /></ItemGroup></Project>
