<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/server/modules/SyntheticFixPackages/SyntheticFixPackages.csproj" />
  </ItemGroup>
  <ItemGroup><None Update="*.json" CopyToOutputDirectory="PreserveNewest" /><None Update="*.html" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
</Project>
