<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Identity.Web" Version="[4.15.0]" />
    <ProjectReference Include="../../modules/IdentitySessions/IdentitySessions.csproj" />
    <ProjectReference Include="../../modules/IdentityAuthority/IdentityAuthority.csproj" />
  </ItemGroup>
</Project>
