import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';
const root='/Users/pedrovolu/Documents/ChatGPT/IGAMigrationTool';const web=`${root}/src/web`;const require=createRequire(`${web}/package.json`);const React=require('react');const {renderToStaticMarkup}=require('react-dom/server');const {build}=await import(`${web}/node_modules/vite/dist/node/index.js`);
async function buildModule(entry,path){const result=await build({root:web,configFile:false,logLevel:'silent',build:{ssr:entry,write:false,minify:false,rollupOptions:{external:['react','react/jsx-runtime']}}});let code=result.output.find(chunk=>chunk.type==='chunk').code.replace(/from "react\/jsx-runtime"/g,`from '${web}/node_modules/react/jsx-runtime.js'`).replace(/from "react"/g,`from '${web}/node_modules/react/index.js'`);if(entry.endsWith('/DraftReportView.tsx'))code+='\nexport { DedicatedProjection };\n';await fs.writeFile(path,code);return import(path);}
const current=await buildModule(`${web}/src/DraftReportView.tsx`,'/private/tmp/iga-ui-w5-report-review-current.mjs');
const baseline=execFileSync('/usr/bin/git',['show','HEAD:src/web/src/DraftReportView.tsx'],{cwd:root,encoding:'utf8'}).replace("from './MaturityView'",`from '${web}/src/MaturityView'`);
await fs.writeFile('/private/tmp/iga-ui-w5-report-review-baseline.tsx',baseline);
const previous=await buildModule('/private/tmp/iga-ui-w5-report-review-baseline.tsx','/private/tmp/iga-ui-w5-report-review-previous.mjs');
const records=JSON.parse(await fs.readFile(`${root}/work/ui-review/2026-10-03/approved-platform-implementation/preview-snapshot.json`,'utf8'));
const saved=records.find(([path,value])=>path.endsWith('/analysis')&&value.reportDraft?.status==='Ready')[1].reportDraft;
function freeze(value){if(value&&typeof value==='object'){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;}freeze(saved);
let assertions=0;function ok(condition,message){assert.ok(condition,message);assertions++;}
function render(component,report,dedicated=false){return renderToStaticMarkup(React.createElement(component,{report,dedicated}));}
const before=JSON.stringify(saved);const inline=render(current.DraftReportView,saved);ok(inline===render(previous.DraftReportView,saved),'default inline exact SSR markup unchanged');ok(inline===render(current.DraftReportView,saved,false),'explicit false same as default');ok(render(current.DraftReportView,null)==='','inline null remains blank');
const dedicated=render(current.DraftReportView,saved,true);for(const tab of ['Executive','Practitioner','Auditor','Assessment quality','Publication history'])ok(dedicated.includes(`>${tab}</button>`),'approved exact tab '+tab);ok((dedicated.match(/aria-pressed="true"/g)||[]).length===1,'one selected audience');ok(dedicated.includes('data-report-audience="Executive"'),'Executive default');ok(dedicated.includes(saved.snapshot.canonicalContentDigest),'canonical digest preserved');ok(dedicated.includes(saved.markdown.markdownSha256),'Markdown digest preserved');ok(dedicated.includes('Synthetic draft · Unpublished'),'not published');ok(dedicated.includes('inert Markdown preview'),'Markdown disclosed only');
for(const report of [null,{...saved,status:'Unavailable'},{...saved,snapshot:null},{...saved,markdown:null},{...saved,markdown:{...saved.markdown,canonicalContentDigest:'mismatch'}}]){const html=render(current.DraftReportView,report,true);ok((html.match(/aria-pressed=/g)||[]).length===5,'unavailable branch retains five controls');ok(!html.includes('data-report-audience='),'incoherent draft does not render saved projection');ok(html.includes('No admitted canonical draft')||html.includes('A coherent draft could not be verified'),'unavailable report explicit');}
for(const audience of ['Executive','Practitioner','Auditor','Assessment quality','Publication history']){const html=renderToStaticMarkup(React.createElement(current.DedicatedProjection,{audience,snapshot:saved.snapshot}));ok(html.length>100,'projection available '+audience);ok(!html.includes('href='),'no fabricated or active links '+audience);if(audience==='Publication history'){ok(html.includes('Publication history is unavailable'),'publication rows unavailable');ok(html.includes('disabled=""'),'publication action disabled');ok(!html.includes('Sample consultant'),'no fabricated publisher');}if(audience==='Auditor'){ok(html.includes(saved.snapshot.canonicalContentDigest),'Auditor canonical provenance digest');ok(html.includes('Decisions and provenance'),'Auditor captured decisions');}}
const hostile=structuredClone(saved);hostile.snapshot.content.warnings=['<script>alert("x")</script>'];hostile.snapshot.source.baselineId='<img src=x onerror=alert(1)>';hostile.markdown.markdownText='[link](javascript:alert(1))\n<script>alert(1)</script>';
const hostileHtml=render(current.DraftReportView,hostile,true);ok(!hostileHtml.includes('<script>')&&!hostileHtml.includes('<img'),'source and warnings inert');ok(hostileHtml.includes('&lt;script&gt;'),'hostile raw text escaped');ok(!hostileHtml.includes('href="javascript:'),'markdown cannot activate links');
ok(JSON.stringify(saved)===before,'deep frozen original content/digests unchanged');
const source=await fs.readFile(`${web}/src/DraftReportView.tsx`,'utf8');ok(source.indexOf("const [audience, setAudience]")<source.indexOf('if (report === null)'),'hooks execute before null branch');ok(!source.includes('dangerouslySetInnerHTML'),'no HTML injection');
console.log(JSON.stringify({result:'pass',assertions,review:'independent nonauthor DraftReportView',scope:['exact inline baseline SSR comparison','five approved audiences','null/unavailable/missing/digest mismatch guards','all audience projections','actual saved canonical content/digest retention','inert hostile source and Markdown','no fabricated publication','hook order'],limits:'interactive audience switching and full browser/reflow checks remain coordinator'},null,2));
