<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../modules/RecommendationGuidance/RecommendationGuidance.csproj" />
    <ProjectReference Include="../../modules/ReportDrafts/ReportDrafts.csproj" />
    <ProjectReference Include="../../modules/AssessmentRuns/AssessmentRuns.csproj" />
    <ProjectReference Include="../../modules/FindingReview/FindingReview.csproj" />
  </ItemGroup>
</Project>
