<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><AssemblyName>LocalPlanningTasks.IntegrationTests</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../../../src/server/hosts/LocalConsultantDemo/LocalConsultantDemo.csproj" /><ProjectReference Include="../../../src/server/modules/SyntheticPlanningTasks/SyntheticPlanningTasks.csproj" /></ItemGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App" /><None Update="*.json" CopyToOutputDirectory="PreserveNewest" /></ItemGroup></Project>
