import json,hashlib,pathlib
p=pathlib.Path(__file__).resolve().parent
a='a'*64;b='b'*64;c='c'*64
scope=dict(customerId='synthetic-customer',projectId='synthetic-project',environmentId='synthetic-environment')
run='7eedaf91-6e83-4e82-8b2b-deefc910b27b'
versions=dict(profileVersion='synthetic-profile-v1',desiredOutcomeVersion=None,scoringAlgorithmVersion='pilot-health-v1',aiPolicyVersion='synthetic-ai-disabled-v1',promptVersion='synthetic-prompt-disabled-v1',modelVersion='synthetic-model-disabled-v1',applicationVersion='synthetic-review-maturity-app-v1',workSchemaVersion='synthetic-run-work-v1',scriptedResultsDigest=a,analysisFixtureDigest=a,maturityFixtureDigest=a)
cap=dict(matrixVersion='synthetic-analysis-matrix-v1',stateAtLock='FixtureVerified',productBuild='fixture-product-v1',databaseSchemaBuild='fixture-facts-v1',hotfixSetDigest='synthetic-hotfix-digest',sqlServerBuild='synthetic-sql-build',compatibilityLevel=160,modules=[dict(id='SyntheticOperations',version='synthetic-module-v1'),dict(id='SyntheticSecurity',version='synthetic-module-v1')],queryPackVersion='synthetic-query-pack-v1',normalizationSchemaVersion='synthetic-normalization-v1',ruleCatalogVersion='synthetic-analysis-catalog-v1',lockDigest=a)
analysis=dict(scope=scope,packVersion='synthetic-analysis-pack-v1',packDigest=a,presetId='synthetic-analysis-findings-v1',presetVersion='synthetic-evidence-v1',evidenceDigest=a,catalogVersion='synthetic-analysis-catalog-v1',catalogDigest=a,profileId='synthetic-analysis-equal-v1',profileVersion='synthetic-profile-v1',profileDigest=a,compatibility=dict(sourceProduct='SYNTHETIC-ONLY',productVersion='fixture-product-v1',evidenceSchemaVersion='fixture-facts-v1',ruleLanguageVersion='count-predicate-v1'))
source=dict(scope=scope,runId=run,runRevision=13,runState='Scoring',runInputDigest=a,baselineId='synthetic-analysis-findings-v1',profileId='synthetic-review-maturity-equal-v1',frozenVersions=versions,capabilityLock=cap,analysisLock=analysis,analysisFixtureDigest=a,analysisContentDigest=a,savedCoverageDigest=a,reviewRunId=run,reviewRunRevision=13,reviewSnapshotDigest=a)
occ=dict(occurrenceId=c,objectId='OBJECT-1',objectType='SyntheticControl',moduleId='SyntheticSecurity',originalDigest=a,evidenceReference='fixture-evidence:OBJECT-1')
opt=dict(optionId='inspect-fixture',text='Inspect the original fixture.',prerequisites='Consultant review required.',risk='Unverified; do not execute.',recoveryGuidance='Retain the prior baseline.')
finding=dict(findingId=b,ruleId='SYN-GUARD',ruleVersion='synthetic-rule-v1',categoryId='SECURITY',severity='Critical',originalTitle='Original fictional title',presentationTitle='Current fictional title',businessContext='Synthetic business context',initialState='Proposed',currentState='Confirmed',findingRevision=1,rootCause='Fictional root cause',occurrences=[occ],options=[opt],validationGuidance=['Verify exact rule and baseline.','New evidence is required.'],guidanceReferences=['fixture-guidance:SYN-GUARD:v1'],assumptions=['Fictional fixture premise.'],limitations=['No customer validation.'])
payload=dict(schemaVersion='synthetic-recommendation-guidance-v1',status='SyntheticUnverified',source=source,findings=[finding],warnings=['Synthetic fixture guidance only; no actual One Identity defect, supported remediation or customer approval is established.','Every option is review-only and unverified. Finding confirmation, rejection or deferral does not review guidance or validate remediation.','Stable identity ordering is not a priority calculation. Recovery guidance does not establish executed or verified restoration.','This is a current detached value, not durable recommendation history. The run remains Scoring and unpublished.'],unavailableSections=['Priority calculation, effort estimates and consultant overrides are unavailable.','Customer-approved objectives, roles and approvals are unavailable.','Fix artifacts, recommendation review, task conversion/workflows and CSV export are unavailable.','Customer risk acceptance, validated remediation, reassessment and actual report publication/sharing are unavailable.','No SQL, script, configuration artifact, customer-system execution, external task connector or ROI calculation exists.'])
canonical=lambda x:json.dumps(x,sort_keys=True,separators=(',',':'),ensure_ascii=True)
optionHash=hashlib.sha256(canonical(dict(findingId=b,optionId='inspect-fixture',runId=run,scope=scope)).encode()).hexdigest()
finding['options'][0]=dict(scopedOptionId=optionHash,status='Unverified',**opt)
golden=canonical(payload)
assert (p/'golden-payload.json').read_bytes() == golden.encode('utf-8')
assert optionHash == '39132c2bfb9e8b3d13a6badd1c9569f989867264039cd258bacfe97f21dc328d'
assert hashlib.sha256(golden.encode('utf-8')).hexdigest() == 'd141e78843b8df1307b98f4d3f80724574c8c7177a6e87fb9c70035b789d6b46'
print('PASS independent literal golden bytes and option/content SHA256')
